# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_commentlikemodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
